### ISSUE TITLE
Upgrade to Cosmos SDK v0.50

### ISSUE THREAD

**Issue by johnletey** [monerium/module-noble#2]
Now that the `v1.0.0` release tag has been cut, the Noble team will start working on upgrading the module to the latest stable release of the Cosmos SDK. Below, you can find a list of tasks we will complete and open PRs for!

- [x] Update module path to include a `v2` suffix. This is to follow standard go versioning [best practices](https://go.dev/ref/mod#major-version-suffixes).
	- #3
- [x] Update Protobuf definitions to be compatible with Cosmos SDK v0.50, utilizing their [builder](https://ghcr.io/cosmos/proto-builder).
	- #4
- [x] Bump Cosmos SDK and CometBFT to the latest patch release of `v0.50.x`, ensuring builds and tests still work.
	- #5
- [x] Support App Wiring to be compatible with the latest Noble codebase.
	- #6 
	- We have decided against supporting AutoCLI in this upgrade as we have multiple custom query commands, and AutoCLI doesn't support maps currently. Support can be added at a later time via a quality of life upgrade.
- [x] Reorganize repository structure to align with Noble's standard.
	- #7
- [x] Utilize [collections](https://docs.cosmos.network/v0.50/build/packages/collections) for managing state, simplifying and removing a lot of boilerplate code. @spoo-bar
	- #10

Any other items will be added adhoc to this list as they come up!

**Comment by johnletey** [comment]
Thanks for your patience and all the reviews @gislik! Can finally mark this as complete 🚀

**Comment by gislik** [comment]
Well done @johnletey absolute pleasure.
